### ISSUE TITLE
BuildSystemEngine 报错

### ISSUE THREAD

**Issue by fansmc** [AppCanOpenSource/appcan-android#148]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java_lang_String$substring$2.call(Unknown Source)
        at com.appcan.AppCanPlugin.getEngineZipVersion(AppCanPlugin.groovy:151)
执行gradle task  buildSystemEngine 报错

**Comment by sandy1108** [comment]
怀疑你可能修改了BConstants类的版本号。
